stages:
  - test
  - version
  - release

default:
  image: registry.mdcatapult.io/informatics/docker-images/ci:golang-v1.0.1

lint:
  stage: test
  script:
    - go vet ./...
    - golangci-lint run

test:
  stage: test
  script: 
    - go test ./... -coverpkg=./... -coverprofile=cover.out
    - go tool cover -func cover.out
  coverage: /total:\s+\(statements\)\s+(\d+.\d+\%)/

release:
  stage: release
  script:
    - export GITLAB_TOKEN=$GIT_RELEASE_TOKEN
    - goreleaser release --rm-dist
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

version:
  stage: release
  script:
    - . /scripts/utils.sh
    - . /scripts/setup-git.sh
    - . /scripts/export-env.sh --branches --rebase develop
    - . /scripts/version.sh
    - . /scripts/rebase.sh
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/