stages:
  - test
  - version
  - release

default:
  image: registry.mdcatapult.io/informatics/docker-images/ci:golang-v1.1.0

lint:
  stage: test
  tags:
    - wopr
  script:
    - go vet ./...
    - golangci-lint run

test:
  stage: test
  tags:
    - wopr
  script: 
    - go test ./... -coverpkg=./... -coverprofile=cover.out
    - go tool cover -func cover.out
  coverage: /total:\s+\(statements\)\s+(\d+.\d+\%)/

release:
  stage: release
  tags:
    - wopr
  script:
    - export GITLAB_TOKEN=$GIT_RELEASE_TOKEN
    - goreleaser release --rm-dist
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

version:
  stage: release
  tags:
    - wopr
  script:
    - /scripts/release.sh -N -b -r develop
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/